# Generated by Django 5.1.6 on 2025-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0003_alter_vendor_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('sw', 'Swahili'), ('rw', 'Kinyarwanda'), ('rn', 'Rundi')], default='en', max_length=2),
        ),
    ]
