# Generated by Django 5.1.6 on 2025-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('RWF', 'Rwandan Francs'), ('BIF', 'Burundian Francs')], default='BIF', max_length=3),
        ),
    ]
