# Generated by Django 5.1.6 on 2025-02-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0005_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
