# Generated by Django 5.1.6 on 2025-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0006_alter_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricealert',
            old_name='target_price',
            new_name='change_amount',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='change_type',
            field=models.CharField(default='increased', max_length=20),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
