# Generated by Django 5.1.6 on 2025-03-07 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0006_priceinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza.category')),
            ],
        ),
    ]
