# Generated by Django 5.1.6 on 2025-03-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0007_aisuggestedprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
