# Generated by Django 5.1.6 on 2025-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0010_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
