# Generated by Django 5.1.6 on 2025-02-09 21:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0011_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproduct',
            unique_together={('user', 'product')},
        ),
    ]
