# Generated by Django 5.1.6 on 2025-02-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0012_alter_savedproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='saved_preferred_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
