# Generated by Django 5.1.6 on 2025-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baza', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('electronics', 'Electronics'), ('apparel_fashion', 'Apparel & Fashion'), ('health_beauty', 'Health & Beauty'), ('home_garden', 'Home & Garden'), ('sports_outdoors', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('toys_games', 'Toys & Games'), ('books_music_media', 'Books, Music & Media'), ('office_supplies', 'Office Supplies'), ('tools_hardware', 'Tools & Hardware'), ('pet_supplies', 'Pet Supplies'), ('baby_kids_products', 'Baby & Kids’ Products'), ('jewelry_accessories', 'Jewelry & Accessories'), ('arts_crafts_hobbies', 'Arts, Crafts & Hobbies'), ('industrial_scientific', 'Industrial & Scientific')], max_length=100),
        ),
    ]
